spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: y6263309
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.163.com
    username: 15160284336@163.com
    password: JACYFGHVJTVZFBRS
    port: 465
    properties:
      from: javastudy111@163.com
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true